V1
laravelindo/memento pull request #4
Opened 2023-07-05 06:52 UTC by hansenjonatann

2023-07-05 07:43 UTC, satucl commented
aku close karena ini cuma test

2023-07-05 07:50 UTC, satucl requested changes

2023-07-05 07:50 UTC, satucl commented on resources/views/version1.blade.php
> +Testing Version 1 in branch v1
coba ganti version 1 jadi version 2. teksnya aja. ini cuma ngetes, kalo adaa revisi, bisa ga kamu push ulang. kalo bingung, tanya aku di slack ya

2023-07-05 15:07 UTC, hansenjonatann commented on resources/views/version1.blade.php
> +Testing Version 1 in branch v1
ok kak

2023-07-06 20:35 UTC, closed without merging

2023-07-06 20:36 UTC, satucl commented
aku close karena percobaan kita udah beres. hansen udah bisa bikin PR dan revisi